app: myapp
service: hello-world

# stages key is v4 only, v3 needs param to have a default like seen below under custom
stages: 
  dev01:
    observability: false
    params:
      duplo: true
  

provider:
  name: aws
  runtime: nodejs20.x
  timeout: 30  
  stage: dev01
  region: us-west-2
  tags:
    App: "${self:app}"

custom:
  duplocloud:
    tenant: ${opt:stage}
    usePrefix: true
    # only v3 needs the default below because it cannot be set under stages
    enabled: ${param:duplo,false}

functions:
  helloworld:
    description: Hello world
    handler: index.handler

plugins:
- serverless-duplocloud
