name: NPM Package

on:
  workflow_dispatch: 
    inputs:
      action:
        description: Version to bump to
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major
          - premajor
          - preminor
          - prepatch
      push:
        description: Push the artifact to npmjs?
        default: false
        type: boolean

jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment: 
      name: npmjs
      url: https://www.npmjs.com/package/serverless-duplocloud
    steps:

    - name: Setup
      id: setup
      uses: duplocloud/serverless/.github/actions/setup@main
      with:
        app-id: ${{ vars.GH_APP_ID }}
        private-key: ${{ secrets.GH_APP_KEY }}

    - name: NPM Version
      id: version
      env:
        ACTION: ${{ inputs.action }}
      run: |
        TAG=$(npm version "$ACTION" --no-git-tag-version)
        echo "tag=$TAG" >> "$GITHUB_OUTPUT"

    - name: Build
      id: build
      run: npm run build -- --removeComments

    - name: Pack
      id: pack
      run: npm pack

    - name: Github Artifact
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: serverless-duplocloud-*.tgz

    - name: Bump Version
      id: bump
      uses: duplocloud/version-action@main
      with:
        version: ${{ steps.version.outputs.tag }}
        push: ${{ inputs.push }}
        token: ${{ steps.setup.outputs.token }}
        files: package.json

    - name: Publish
      id: publish
      if: inputs.push
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npm publish --provenance --access public

    - name: Create Release
      id: release
      if: inputs.push
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ steps.setup.outputs.token }}
        name: ${{ steps.bump.outputs.tag }}
        tag_name: ${{ steps.bump.outputs.tag }}
        prerelease: false
        body: |
          [![Publish](${{ github.server_url }}/${{ github.repository }}/actions/workflows/publish.yml/badge.svg)](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) [![NPM Version](https://img.shields.io/npm/v/serverless-duplocloud)](https://www.npmjs.com/package/serverless-duplocloud)

          ${{ steps.bump.outputs.release-notes }}

    - name: Summary
      run: |
        cat <<EOF > "$GITHUB_STEP_SUMMARY"
        [![Release](https://img.shields.io/badge/Github-Release-blue?style=flat-square&logo=github)](${{ steps.release.outputs.url || '' }})
        
        New Version: ${{ steps.bump.outputs.version }}
        Previous Version: ${{ steps.bump.outputs.previous-version }}

        Release Notes: 
        --------------
        ${{ steps.bump.outputs.release-notes }}
        EOF
