name: 🪢 Pull Request

on:
  pull_request:
    branches:
    - main

jobs: 

  changelog_check:
    name: Changelog Updated
    runs-on: ubuntu-latest
    steps:
    - name: Make sure changes are logged
      uses: tarides/changelog-check-action@v3
      with:
        changelog: CHANGELOG.md

  test:
    name: Test
    uses: ./.github/workflows/test.yml
    secrets: inherit

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    needs: test
    permissions:
      checks: write
      pull-requests: write
      contents: write
    steps:

    - name: Download coverage report
      uses: actions/download-artifact@v4
      with:
        name: coverage
        path: coverage

    - name: Generate PR Coverage Report
      id: coverage
      uses: ArtiomTr/jest-coverage-report-action@v2
      with:
        skip-step: all
        output: report-markdown
        coverage-file: ./coverage/report.json
        base-coverage-file: ./coverage/report.json

    - name: Update PR
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        message: ${{ steps.coverage.outputs.report }}
